### ISSUE TITLE
Haven't been successful running a single Ansible playbook over fortinet

### ISSUE THREAD

**Issue by shariaty59** [fortinet-solutions-cse/ansible_generator#16]
after spending almost 15 hours reading ansible network modules documents on fortinet, I just took one of the examples "fortios_firewall_policy_example.yml" that says should work straightforward and it is not.

TASK [fortios_firewall_policy] ************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (fortios_firewall_policy) module: ssl_verify, state Supported parameters include: firewall_policy, host, https, password, username, vdom"}

I commented out  ssl_verify and state. now I am getting this:

TASK [fortios_firewall_policy] ************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (fortios_firewall_policy) module: logtraffic_start found in firewall_policy. Supported parameters include: action, app-category, app-group, application, application-list, auth-cert, auth-path, auth-redirect-addr, av-profile, block-notification, ...

I just need a single ansible playbook that I can run on a fortinet firewall and I was hoping these examples could give me that :(

**Comment by frankshen01** [comment]
Hi @shariaty59 

Sample Steps for Configuring FortiGate Firewall with Ansible:

1 Make sure that you have installed Ansible successfully:
```
# ansible --version
ansible 2.10.0.dev0
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /samba/01ansible_dev/zzzzzz/ansible/lib/ansible
  executable location = /samba/01ansible_dev/zzzzzz/ansible/bin/ansible
  python version = 3.7.3 (default, Oct  7 2019, 12:56:13) [GCC 8.3.0]

```

2 Create a simple playbook

```
# cat 001Test.yml
- hosts: localhost
  vars:
   host: "192.168.52.177"
   username: "admin"
   password: "admin"
   vdom: "root"
   ssl_verify: "False"
  tasks:
  - name: Configure global attributes.
    fortios_system_global:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "True"
      ssl_verify:  "{{ ssl_verify }}"
      system_global:
        admintimeout: "23"
        hostname: "myhostname"

```


3 Run with ansible:
```
# ansible-playbook 001Test.yml
```
You should find the name of your fortigate has been changed to “myhostname”.


Thanks,

**Comment by shariaty59** [comment]
@frankshen01 Hi, Thank you for your response. 

Step1. checking the Ansible version:

```
$ ansible --version
ansible 2.8.6
  config file = None
  configured module search path = ['/home/ashariaty/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```
Step2. putting the playbook together:

```
---
- hosts: localhost
  vars:
    host: "10.20.119.10"
    username: "admin"
    password: "admin"
    vdom: "root"
    ssl_verify: "False"

  tasks:
  - name: Configure global attributes.
    fortios_system_global:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "True"
      ssl_verify:  "{{ ssl_verify }}"
      system_global:
        admintimeout: "23"
        hostname: "myhostname"
```

Step3. Running the playbook gives me this error:

```
TASK [Configure global attributes.] ********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (fortios_system_global) module: ssl_verify Supported parameters include: host, https, password, system_global, username, vdom"}
```
it seems like it does not even try my fortigate firewall. the issue is with the module itself.
any ideas?
