### ISSUE TITLE
Issue in generated fortios_system_interface -> allowedaccess

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-solutions-cse/ansible_generator#6]
Please see generated output in https://github.com/fortinet-solutions-cse/ansible_fgt_modules/blob/master/v6.0.2/system/fortios_system_interface.py#L1781-L1785

Currently, this only permits setting a single item ("one of" ['ping', 'http', 'https', ... etc]) instead of being able to select individual items.

*ideally* this would be an options list:

```
  - name: Configure interfaces.
    fortios_system_interface:
      system_interface:
        state: present
        allowaccess:
          ping: True
          http: False
          https: True
          fgfm: False
        interface: port1
```

Without digging into either the ansible_generator, [fortiosapi](https://github.com/fortinet-solutions-cse/fortiosapi) or the [generated ansible module](https://github.com/fortinet-solutions-cse/ansible_fgt_modules] code, I can't express whether this is the "right way" to do this, or even if it's a "feasible" way to do it.

Also, FAO @tohillm
